# Site settings
site: labexam
title: labexam
keywords: labexam, blog
description: >-
  Ephesus - Minimalist Jekyll Theme
lang: en-US
timezone:  Europe/Istanbul
repo: https://attilaroshani.github.io/labexam/ # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Attila Roshani khiyavy
  bio: Computer Engineering student @iust <br> Founder @AtiaRoshani <br> Open Source /#linux
  picture: assets/images/profile.jpg 
  github: onepase # github username
  twitter: AUrushan # twitter username
  instagram: attila_roshani # instagram username
  linkedin: Attila Roshani # linkedin username
  email: atilaroshani@gmail.com # email adress


# URL settings
url: "https://attilaroshani.github.io/labexam/" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false